H5P.MarkTheWords=H5P.MarkTheWords||{};H5P.MarkTheWords.Word=(function(){Word.ID_MARK_MISSED="h5p-description-missed";Word.ID_MARK_CORRECT="h5p-description-correct";Word.ID_MARK_INCORRECT="h5p-description-incorrect";function Word($word,params){var self=this;self.params=params;H5P.EventDispatcher.call(self);var input=$word.text();var handledInput=input;var isAnswer=checkForAnswer();handleAsterisks();if(isAnswer){$word.text(handledInput);}
const ariaText=document.createElement('span');ariaText.classList.add('hidden-but-read');$word[0].appendChild(ariaText);function checkForAnswer(){var wordString=removeDoubleAsterisks(input);if(wordString.charAt(0)===('*')&&wordString.length>2){if(wordString.charAt(wordString.length-1)===('*')){handledInput=input.slice(1,input.length-1);return true;}
else if(wordString.charAt(wordString.length-2)===('*')){handledInput=input.slice(1,input.length-2);return true;}
return false;}
return false;}
function removeDoubleAsterisks(wordString){var asteriskIndex=wordString.indexOf('*');var slicedWord=wordString;while(asteriskIndex!==-1){if(wordString.indexOf('*',asteriskIndex+1)===asteriskIndex+1){slicedWord=wordString.slice(0,asteriskIndex)+wordString.slice(asteriskIndex+2,input.length);}
asteriskIndex=wordString.indexOf('*',asteriskIndex+1);}
return slicedWord;}
function handleAsterisks(){var asteriskIndex=handledInput.indexOf('*');while(asteriskIndex!==-1){handledInput=handledInput.slice(0,asteriskIndex)+handledInput.slice(asteriskIndex+1,handledInput.length);asteriskIndex=handledInput.indexOf('*',asteriskIndex+1);}}
self.clearScorePoint=function(){const scorePoint=$word[0].querySelector('div');if(scorePoint){scorePoint.parentNode.removeChild(scorePoint);}};this.getText=function(){return input;};this.markClear=function(){$word.attr('aria-selected',false).removeAttr('aria-describedby');ariaText.innerHTML='';this.clearScorePoint();};this.markCheck=function(scorePoints){if(this.isSelected()){$word.attr('aria-describedby',isAnswer?Word.ID_MARK_CORRECT:Word.ID_MARK_INCORRECT);ariaText.innerHTML=isAnswer?self.params.correctAnswer:self.params.incorrectAnswer;if(scorePoints){$word[0].appendChild(scorePoints.getElement(isAnswer));}}
else if(isAnswer){$word.attr('aria-describedby',Word.ID_MARK_MISSED);ariaText.innerHTML=self.params.missedAnswer;}};this.isCorrect=function(){return(isAnswer&&this.isSelected());};this.isWrong=function(){return(!isAnswer&&this.isSelected());};this.isMissed=function(){return(isAnswer&&!this.isSelected());};this.isAnswer=function(){return isAnswer;};this.isSelected=function(){return $word.attr('aria-selected')==='true';};this.setSelected=function(){$word.attr('aria-selected','true');};}
Word.prototype=Object.create(H5P.EventDispatcher.prototype);Word.prototype.constructor=Word;return Word;})();