H5P.Summary=(function($,Question,XApiEventBuilder,StopWatch){var summaryId=0;function Summary(options,contentId,contentData){if(!(this instanceof H5P.Summary)){return new H5P.Summary(options,contentId);}
this.id=this.contentId=contentId;this.contentData=contentData;this.summaryId=summaryId;Question.call(this,'summary');this.offset=0;this.score=0;this.progress=0;this.answers=[];this.answer=[];this.errorCounts=[];summaryId+=1;this.userResponses=[];this.dataBitMap=[];if(options.summaries){options.summaries=options.summaries.filter(function(element){return element.summary!==undefined;});}
if(contentData&&contentData.previousState!==undefined&&contentData.previousState.progress!==undefined&&contentData.previousState.answers){this.progress=contentData.previousState.progress||this.progress;this.answers=contentData.previousState.answers||this.answers;var currentProgress=this.progress;if(this.progress>=options.summaries.length){currentProgress=options.summaries.length-1;}
for(var i=0;i<=currentProgress;i++){if(this.errorCounts[i]===undefined){this.errorCounts[i]=0;}
if(this.answers[i]){this.score+=this.answers[i].length;this.errorCounts[i]++;}}}
var that=this;this.stopWatches=[];this.startStopWatch(this.progress);this.options=H5P.jQuery.extend({},{overallFeedback:[],resultLabel:"Your result:",intro:"Choose the correct statement.",solvedLabel:"Solved:",scoreLabel:"Wrong answers:",labelCorrect:"Correct.",labelIncorrect:'Incorrect! Please try again.',labelCorrectAnswers:"List of correct answers.",alternativeIncorrectLabel:'Incorrect',postUserStatistics:(H5P.postUserStatistics===true),tipButtonLabel:'Show tip',scoreBarLabel:'You got :num out of :total points',progressText:'Progress :num of :total'},options);this.summaries=that.options.summaries;this.setBehaviour({disableReadSpeaker:true});this.showSolutions=function(){};this.getMaxScore=function(){return this.summaries?this.summaries.length:0;};this.getScore=function(){var self=this;return self.summaries?self.summaries.reduce(function(result,panel,index){var userResponse=self.userResponses[index]||[];return result+(self.correctOnFirstTry(userResponse)?1:0);},0):0;};this.getTitle=function(){return H5P.createTitle((this.contentData&&this.contentData.metadata&&this.contentData.metadata.title)?this.contentData.metadata.title:'Summary');};this.getCurrentState=function(){return{progress:this.progress,answers:this.answers};};}
Summary.prototype=Object.create(Question.prototype);Summary.prototype.constructor=Summary;Summary.prototype.registerDomElements=function(){this.setContent(this.createQuestion());};Summary.prototype.createQuestion=function(){var that=this;var id=0;var currentFocusedOption;var elements=[];var $=H5P.jQuery;this.$myDom=$('<div>',{'class':'summary-content'});this.$answerAnnouncer=$('<div>',{'class':'hidden-but-read','aria-live':'assertive',appendTo:this.$myDom,});if(that.summaries===undefined||that.summaries.length===0){return;}
for(var panelIndex=0;panelIndex<that.summaries.length;panelIndex++){if(!(that.summaries[panelIndex].summary&&that.summaries[panelIndex].summary.length)){continue;}
elements[panelIndex]={tip:that.summaries[panelIndex].tip,summaries:[]};for(var summaryIndex=0;summaryIndex<that.summaries[panelIndex].summary.length;summaryIndex++){var isAnswer=(summaryIndex===0);that.answer[id]=isAnswer;that.dataBitMap[panelIndex]=this.dataBitMap[panelIndex]||[];that.dataBitMap[panelIndex][id]=summaryIndex;if(that.answers[panelIndex]&&(that.answers[panelIndex].indexOf(id)!==-1)){this.storeUserResponse(panelIndex,summaryIndex);}
elements[panelIndex].summaries[summaryIndex]={id:id++,text:that.summaries[panelIndex].summary[summaryIndex]};}
if(panelIndex<that.progress){this.storeUserResponse(panelIndex,0);}
for(var k=elements[panelIndex].summaries.length-1;k>0;k--){var j=Math.floor(Math.random()*(k+1));var temp=elements[panelIndex].summaries[k];elements[panelIndex].summaries[k]=elements[panelIndex].summaries[j];elements[panelIndex].summaries[j]=temp;}}
var $summary_container=$('<div class="summary-container"></div>');var $summary_list=$('<ul role="list" aria-labelledby="answerListHeading-'+that.summaryId+'"></ul>');var $evaluation=$('<div class="summary-evaluation"></div>');var $evaluation_content=$('<div id="questionDesc-'+that.summaryId+'" class="summary-evaluation-content">'+that.options.intro+'</div>');var $score=$('<div class="summary-score"></div>');var $options=$('<div class="summary-options"></div>');var $progress=$('<div class="summary-progress" aria-live="polite"></div>');var $progressNumeric=$('<div class="summary-progress-numeric" aria-hidden="true"></div>');var options_padding=parseInt($options.css('paddingLeft'));var $answersListHeading=$('<div id="answerListHeading-'+that.summaryId+'" class="h5p-hidden-read">'+that.options.labelCorrectAnswers+'</div>');if(this.score){$score.html(that.options.scoreLabel+' '+this.score).show();}
$summary_container.attr("aria-hidden","true");$summary_container.html($answersListHeading);$summary_container.append($summary_list);this.$myDom.append($summary_container);this.$myDom.append($evaluation);this.$myDom.append($options);$evaluation.append($evaluation_content);$evaluation.append($evaluation);$evaluation.append($progress);$evaluation.append($progressNumeric);$evaluation.append($score);var selectedAlt=function($el,setFocus){var nodeId=Number($el.attr('data-bit'));var panelId=Number($el.parent().data('panel'));var isRadioClicked=$el.attr('aria-checked');if(isRadioClicked=='true')return;if(that.errorCounts[panelId]===undefined){that.errorCounts[panelId]=0;}
that.storeUserResponse(panelId,nodeId);if(that.answer[nodeId]){that.announceAnswer(true);that.stopStopWatch(panelId);that.progress++;var position=$el.position();var summary=$summary_list.position();var $answer=$('<li role="listitem">'+$el.html()+'</li>');$progressNumeric.html(that.options.solvedLabel+' '+(panelId+1)+'/'+that.summaries.length);var interpolatedProgressText=that.options.progressText.replace(':num',panelId+1).replace(':total',that.summaries.length);$progress.html(interpolatedProgressText);$el.attr("aria-checked","true");$summary_list.append($answer);$summary_container.addClass('has-results');$summary_container.attr("aria-hidden","false");that.adjustTargetHeight($summary_container,$summary_list,$answer);$answer.css({display:'block',width:$el.css('width'),height:$el.css('height')});$answer.css({position:'absolute',top:position.top,left:position.left});$answer.css({backgroundColor:'#9dd8bb',border:''});setTimeout(function(){$answer.css({backgroundColor:''});},1);var panel=parseInt($el.parent().attr('data-panel'));var $curr_panel=$('.h5p-panel:eq('+panel+')',that.$myDom);var $next_panel=$('.h5p-panel:eq('+(panel+1)+')',that.$myDom);var finished=($next_panel.length===0);$curr_panel.addClass('panel-disabled');$evaluation_content.find('.joubel-tip-container').remove();if(elements[that.progress]!==undefined&&elements[that.progress].tip!==undefined&&elements[that.progress].tip.trim().length>0){$evaluation_content.append(H5P.JoubelUI.createTip(elements[that.progress].tip,{tipLabel:that.options.tipButtonLabel}));}
$answer.animate({top:summary.top+that.offset,left:'-='+options_padding+'px',width:'+='+(options_padding*2)+'px'},{complete:function(){$(this).css('position','').css({width:'',height:'',top:'',left:''});$summary_container.css('height','');var tpadding=parseInt($answer.css('paddingTop'))*2;var tmargin=parseInt($answer.css('marginBottom'));var theight=parseInt($answer.css('height'));that.offset+=theight+tpadding+tmargin+1;$curr_panel.fadeOut('fast',function(){$curr_panel.parent().css('height','auto');if(!finished){that.startStopWatch(that.progress);$next_panel.fadeIn('fast');if(setFocus){$next_panel.children().get(0).focus();}}else{$evaluation_content.html(that.options.resultLabel);that.doFinalEvaluation();}
that.trigger('resize');});}});}
else{that.announceAnswer(false);$el.off('click');$el.addClass('summary-failed');const label=that.options.alternativeIncorrectLabel+'. '
+$el.text();$el.attr('aria-label',label);$el.removeClass('summary-claim-unclicked');$el.attr("aria-checked","true");$evaluation.children('.summary-score').css('display','block');$score.html(that.options.scoreLabel+' '+(++that.score));that.errorCounts[panelId]++;if(that.answers[panelId]===undefined){that.answers[panelId]=[];}
that.answers[panelId].push(nodeId);}
that.trigger('resize');that.triggerXAPI('interacted');if(that.userResponses[panelId].length===1){that.trigger(that.createXApiAnsweredEvent(that.summaries[panelId],that.userResponses[panelId]||[],panelId,that.timePassedInStopWatch(panelId)));}
if(finished){that.triggerXAPIScored(that.getScore(),that.getMaxScore(),'answered');}};$progressNumeric.html(that.options.solvedLabel+' '+this.progress+'/'+that.summaries.length);var interpolatedProgressText=that.options.progressText.replace(':num',that.progress).replace(':total',that.summaries.length);$progress.html(interpolatedProgressText);for(var i=0;i<elements.length;i++){var element=elements[i];if(i<that.progress){for(var j=0;j<element.summaries.length;j++){var sum=element.summaries[j];if(that.answer[sum.id]){$summary_list.append('<li style="display:block">'+sum.text+'</li>');$summary_container.addClass('has-results');break;}}}
var $page=$('<ul aria-labelledby="questionDesc-'+that.summaryId+'" role="radiogroup" class="h5p-panel" data-panel="'+i+'"></ul>');if(i==0&&element.tip!==undefined&&element.tip.trim().length>0){$evaluation_content.append(H5P.JoubelUI.createTip(element.tip,{tipLabel:that.options.tipButtonLabel}));}
for(var j=0;j<element.summaries.length;j++){var summaryLineClass='summary-claim-unclicked';if(that.progress===i&&that.answers[that.progress]){for(var k=0;k<that.answers[that.progress].length;k++){if(that.answers[that.progress][k]===element.summaries[j].id){summaryLineClass='summary-failed';break;}}}
var $node=$(''+
'<li role="radio" aria-checked="false" data-name="'+j+'" data-bit="'+element.summaries[j].id+'" class="'+summaryLineClass+'">'+
element.summaries[j].text+
'</li>');(j==0)?$node.attr("tabindex","0"):$node.attr("tabindex","-1");$node.on('focus',function(){var ind=$(this).attr('data-name');setFocusIndex(ind);});var setFocusIndex=function(idx){currentFocusedOption=idx;};if(summaryLineClass==='summary-failed'){$page.append($node);continue;}
$node.click(function(){selectedAlt($(this));}).keydown(function(e){switch(e.which){case 13:case 32:selectedAlt($(this),true);e.preventDefault();break;case 37:case 38:that.gotoPreviousOption(that,currentFocusedOption);e.preventDefault();break;case 39:case 40:that.gotoNextOption(that,currentFocusedOption);e.preventDefault();break;}});$page.append($node);}
$options.append($page);}
if(that.progress===elements.length){$evaluation_content.html(that.options.resultLabel);that.doFinalEvaluation();}
else{$('.h5p-panel:eq('+(that.progress)+')',that.$myDom).css({display:'block'});if(that.progress){that.offset=($('.summary-claim-unclicked:visible:first',that.$myDom).outerHeight()*that.errorCounts.length);}}
that.trigger('resize');return this.$myDom;};Summary.prototype.announceAnswer=function(isCorrect){const announcement=isCorrect?this.options.labelCorrect:this.options.labelIncorrect;this.$answerAnnouncer.html(announcement);setTimeout(function(){this.$answerAnnouncer.html('');}.bind(this),100);};Summary.prototype.getAnswerGiven=function(){return this.errorCounts.length>0;};Summary.prototype.gotoPreviousOption=function(that,currentFocusedOption){this.currentFocusedOption=currentFocusedOption;var totOptions=that.summaries[that.progress].summary.length;var prevRadioEle=$("ul[data-panel="+that.progress+"] li[role='radio']",this.$myDom);prevRadioEle.attr("tabindex","-1");this.currentFocusedOption--;if(this.currentFocusedOption<0){var num=totOptions-1;prevRadioEle.eq(num).attr("tabindex","0");prevRadioEle.eq(num).focus();}
else{prevRadioEle.eq(this.currentFocusedOption).attr("tabindex","0");prevRadioEle.eq(this.currentFocusedOption).focus();}};Summary.prototype.gotoNextOption=function(that,currentFocusedOption){this.currentFocusedOption=currentFocusedOption;var totOptions=that.summaries[that.progress].summary.length;var nextRadioEle=$("ul[data-panel="+that.progress+"] li[role='radio']",this.$myDom);nextRadioEle.attr("tabindex","-1");this.currentFocusedOption++;if(this.currentFocusedOption==totOptions){nextRadioEle.eq(0).attr("tabindex","0");nextRadioEle.eq(0).focus();}
else{nextRadioEle.eq(this.currentFocusedOption).attr("tabindex","0");nextRadioEle.eq(this.currentFocusedOption).focus();}};Summary.prototype.doFinalEvaluation=function(){var that=this;var errorCount=this.countErrors();var maxScore=that.summaries.length;var score=maxScore-errorCount;var percent=100-(errorCount/that.errorCounts.length*100);var summary=H5P.Question.determineOverallFeedback(that.options.overallFeedback,percent/100).replace('@score',score).replace('@total',maxScore).replace('@percent',Math.round(percent));$(".summary-evaluation-content",this.$myDom).removeAttr("tabindex");var scoreBarLabel=that.options.scoreBarLabel.replace(':num',score).replace(':total',maxScore);this.setFeedback(summary,score,maxScore,scoreBarLabel);setTimeout(function(){that.setBehaviour({disableReadSpeaker:false});that.readFeedback();that.read(scoreBarLabel);},3000);that.trigger('resize');};Summary.prototype.resetTask=function(){};Summary.prototype.adjustTargetHeight=function(container,elements,el){var new_height=parseInt(elements.outerHeight())+parseInt(el.outerHeight())+parseInt(el.css('marginBottom'))+parseInt(el.css('marginTop'));if(new_height>parseInt(container.css('height'))){container.animate({height:new_height});}};Summary.prototype.countErrors=function(){var error_count=0;for(var i=0;i<this.summaries.length;i++){if(this.errorCounts[i]===undefined){error_count++;}
else{error_count+=this.errorCounts[i]?1:0;}}
return error_count;};Summary.prototype.getXApiChoices=function(answers){var choices=answers.map(function(answer,index){return XApiEventBuilder.createChoice(index.toString(),answer);});return{choices:choices};};Summary.prototype.storeUserResponse=function(questionIndex,answerIndex){var self=this;if(self.userResponses[questionIndex]===undefined){self.userResponses[questionIndex]=[];}
self.userResponses[questionIndex].push(this.dataBitMap[questionIndex][answerIndex]);};Summary.prototype.startStopWatch=function(index){this.stopWatches[index]=this.stopWatches[index]||new StopWatch();this.stopWatches[index].start();};Summary.prototype.stopStopWatch=function(index){if(this.stopWatches[index]){this.stopWatches[index].stop();}};Summary.prototype.timePassedInStopWatch=function(index){if(this.stopWatches[index]!==undefined){return this.stopWatches[index].passedTime();}
else{return 0;}};Summary.prototype.getTotalPassedTime=function(){return this.stopWatches.filter(function(watch){return watch!==undefined;}).reduce(function(sum,watch){return sum+watch.passedTime();},0);};Summary.prototype.createXApiAnsweredEvent=function(panel,userAnswer,panelIndex,duration){var self=this;var definition=XApiEventBuilder.createDefinition().name('Summary statement').description(self.options.intro).interactionType(XApiEventBuilder.interactionTypes.CHOICE).correctResponsesPattern(['0']).optional(self.getXApiChoices(panel.summary)).build();var result=XApiEventBuilder.createResult().response(userAnswer.join('[,]')).duration(duration).score((self.correctOnFirstTry(userAnswer)?1:0),1).build();return XApiEventBuilder.create().verb(XApiEventBuilder.verbs.ANSWERED).objectDefinition(definition).context(self.contentId,self.subContentId).contentId(self.contentId,panel.subContentId).result(result).build();};Summary.prototype.correctOnFirstTry=function(userAnswer){return(userAnswer.length===1)&&userAnswer[0]===0;};Summary.prototype.getXAPIData=function(){var self=this;var children=self.summaries.map(function(panel,index){var userResponse=self.userResponses[index]||[];var duration=self.timePassedInStopWatch(index);var event=self.createXApiAnsweredEvent(panel,userResponse,index,duration);return{statement:event.data.statement};});var result=XApiEventBuilder.createResult().score(self.getScore(),self.getMaxScore()).duration(self.getTotalPassedTime()).build();var definition=XApiEventBuilder.createDefinition().interactionType(XApiEventBuilder.interactionTypes.COMPOUND).name(self.getTitle()).description(self.options.intro).build();var xAPIEvent=XApiEventBuilder.create().verb(XApiEventBuilder.verbs.ANSWERED).contentId(self.contentId,self.subContentId).context(self.getParentAttribute('contentId'),self.getParentAttribute('subContentId')).objectDefinition(definition).result(result).build();return{statement:xAPIEvent.data.statement,children:children};};Summary.prototype.getParentAttribute=function(attributeName){var self=this;if(self.parent!==undefined){return self.parent[attributeName];}};return Summary;})(H5P.jQuery,H5P.Question,H5P.Summary.XApiEventBuilder,H5P.Summary.StopWatch);