H5P.DragNBarDialog=(function($,EventDispatcher){function Dialog($container,$videoWrapper){var KEY_CODE_ESC=27;var KEY_CODE_ENTER=13;var KEY_CODE_SPACE=32;var self=this;var titleId='dialog-title-'+H5P.createUUID();EventDispatcher.call(self);var stopEventPropagation=function(event){if(event.which===75){event.stopPropagation();}};var $wrapper=$('<div/>',{'class':'h5p-dialog-wrapper h5p-ie-transparent-background h5p-hidden',on:{click:function(){if(!self.disableOverlay){self.close();}},keyup:stopEventPropagation,keydown:stopEventPropagation}});var $dialog=$('<div/>',{'class':'h5p-dialog h5p-big','aria-labelledby':titleId,on:{click:function(event){event.stopPropagation();},keydown:function(event){var isClosable=$close.is(':visible');if(event.which===KEY_CODE_ESC&&isClosable){self.close();}}}}).appendTo($wrapper);var $titleBar=$('<div/>',{'class':'h5p-dialog-titlebar',appendTo:$dialog});var $title=$('<div/>',{'class':'h5p-dialog-title',id:titleId,appendTo:$titleBar});var $close=$('<div/>',{'role':'button','class':'h5p-dialog-close',tabindex:'0',title:H5P.t('close'),'aria-label':H5P.t('close'),on:{click:function(event){if(event.which===1){self.close();}},keypress:function(event){if(event.which===KEY_CODE_SPACE||event.which===KEY_CODE_ENTER){self.close();event.preventDefault();}}},appendTo:$titleBar});var $customButtons;var $inner=$('<div/>',{'class':'h5p-dialog-inner'}).appendTo($dialog);$wrapper.appendTo($container);var resetPosition=function(){$dialog.css({left:'',top:'',height:'',width:'',fontSize:'',bottom:''});$inner.css({width:'',height:'',overflow:''});};var showOverlay=function(next){$wrapper.show();setTimeout(function(){$wrapper.removeClass('h5p-hidden');if(next){next();}},0);};var hideOverlay=function(next){$wrapper.addClass('h5p-hidden');setTimeout(function(){$wrapper.hide();if(next){next();}},200);};self.open=function($element,title,classes,$buttons){showOverlay();$inner.children().detach().end().append($element);resetPosition();$dialog.addClass('h5p-big');$title.attr('class','h5p-dialog-title'+(classes?' '+classes:''));if(!title){title='';}
$title.html(title);if($customButtons){$customButtons.remove();$close.show();}
if($buttons){$customButtons=$buttons;$close.hide();$buttons.appendTo($titleBar);}
self.resize();self.trigger('open');$dialog.one('transitionend',function(){var $inputs=$inner.find('input:visible:not(:disabled)');var $tabbables=$inner.find('[tabindex]');if($inputs.length){$inputs.get(0).focus();}
else if($tabbables.length){$tabbables.get(0).focus();}});};self.resize=function(){if(!$dialog.hasClass('h5p-big')){return;}
var fontSize=toNum($inner.css('fontSize'));var titleBarHeight=($titleBar.outerHeight()/fontSize);var maxHeight=$container.height();maxHeight-=Number($dialog.css('top').replace('px',''))*2;$inner.css({width:'100%',maxHeight:((maxHeight/fontSize)-titleBarHeight)+'em',marginTop:titleBarHeight+'em'});$dialog.css({bottom:'auto',maxHeight:''});};self.addLibraryClass=function(machineName){$dialog.attr('data-lib',machineName);};self.toggleClass=function(cls,toggle){$dialog.toggleClass(cls,toggle);};self.isOpen=function(){return $wrapper.is(':visible');};self.position=function($button,size,type){if(type===true){type='medium';}
resetPosition();$dialog.removeClass('h5p-big h5p-medium');var titleBarHeight=Number($inner[0].style.marginTop.replace('em',''));if(size){var fontSizeRatio=16/toNum($container.css('fontSize'));if(size.width){size.width=(size.width*fontSizeRatio);$dialog.css('width',size.width+'em');}
if(size.height){size.height=(size.height*fontSizeRatio)+titleBarHeight;$dialog.css('height',size.height+'em');$inner.css({width:'auto',overflow:'hidden'});}}
if(type==='medium'){$dialog.addClass('h5p-medium');}
if(type==='big'){$dialog.addClass('h5p-big');$dialog.addClass('h5p-stretch');}
var buttonWidth=$button.outerWidth(true);var buttonPosition=$button.position();var containerWidth=$container.width();var containerHeight=$container.height();var left=buttonPosition.left;var dialogWidth=$dialog.outerWidth(true);if(type==='medium'&&dialogWidth>containerWidth){$dialog.addClass('h5p-big');return;}
if(buttonPosition.left>(containerWidth/2)-(buttonWidth/2)){left-=dialogWidth-buttonWidth;}
if((left+dialogWidth)>containerWidth){left=containerWidth-dialogWidth;}
var marginLeft=parseInt($videoWrapper.css('marginLeft'));if(isNaN(marginLeft)){marginLeft=0;}
if(left<marginLeft){left=marginLeft;}
var marginTop=parseInt($videoWrapper.css('marginTop'));if(isNaN(marginTop)){marginTop=0;}
if(type!=='big'){var top=(type==='medium'?0:(buttonPosition.top+marginTop));var totalHeight=top+$dialog.outerHeight(true);if(totalHeight>containerHeight){top-=totalHeight-containerHeight;}
var maxHeight=$container.height()-top+$dialog.height()-$dialog.outerHeight(true);var fontSize=toNum($container.css('fontSize'));$dialog.css({top:(top/(containerHeight/100))+'%',left:(left/(containerWidth/100))+'%',width:(window.getComputedStyle($dialog[0]).width/fontSize)+'em',maxHeight:(maxHeight/fontSize)+'em'});$inner.css('maxHeight',((maxHeight-$titleBar.outerHeight(true))/fontSize)+'em');}};self.getMaxSize=function($button,fullScreen){var buttonWidth=$button.outerWidth(true);var buttonPosition=$button.position();var containerWidth=$container.width();var max={};max.height=Number($inner.css('maxHeight').replace('px',''));max.height-=Number($inner.css('border-width').replace('px',''))*2;if(fullScreen){max.width=containerWidth;}
else{if(buttonPosition.left>(containerWidth/2)-(buttonWidth/2)){max.width=buttonPosition.left;}
else{max.width=(containerWidth-buttonPosition.left-buttonWidth);}}
var fontSize=toNum($container.css('fontSize'));max.width=(max.width/fontSize)*(fontSize/16);max.height=(max.height/fontSize)*(fontSize/16);return max;};self.scroll=function(to,ms){$inner.stop().animate({scrollTop:to},ms);};self.close=function(closeInstant){$wrapper.addClass('h5p-hidden');if(closeInstant){$wrapper.hide();self.disableOverlay=false;$close.show();}
else{setTimeout(function(){$wrapper.hide();self.disableOverlay=false;$close.show();},201);}
self.trigger('close');self.trigger('domHidden',{'$dom':$wrapper,'key':'dialogClosed'},{'bubbles':true,'external':true});};self.openOverlay=function(){self.disableOverlay=true;$dialog.hide();showOverlay();};self.closeOverlay=function(){$wrapper.addClass('h5p-hidden');hideOverlay(function(){$dialog.show();self.disableOverlay=false;});};self.hideCloseButton=function(){$close.hide();};self.getDialogWidth=function(){return $dialog.width();};self.removeStaticWidth=function(){$dialog.css('width','');};}
Dialog.prototype=Object.create(EventDispatcher.prototype);Dialog.prototype.constructor=Dialog;var toNum=function(num){return Number(num.replace('px',''));};return Dialog;})(H5P.jQuery,H5P.EventDispatcher);